ALTER TABLE ads ADD COLUMN price TEXT;
ALTER TABLE ads ADD COLUMN original_price TEXT;
ALTER TABLE ads ADD COLUMN discount TEXT;
ALTER TABLE ads ADD COLUMN badge TEXT;
ALTER TABLE ads ADD COLUMN installments TEXT;
